apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-argocd
  namespace: bar
  labels:
    app: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: rghdrizzle/weathertrakrfrontend:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
            - containerPort: 80
