apiVersion: v1
kind: Deployment
metadata:
  name: testapp-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp-1
        image: rghdrizzle/drizzlestoragefrontend:v.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
